name: clodder
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

#------Packages------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # Product Specific

  #----------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
          weight: 300
        - asset: assets\fonts\Poppins-BlackItalic.ttf
          weight: 400
          style: italic
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets\fonts\Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets\fonts\Poppins-Thin.ttf
          weight: 300

